name: Publish

on:
  push:
    branches:
      - main
    tags:
      - "!v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.npmToken }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --no-progress

      - name: Build
        run: yarn prepublish:latest

      - name: Run release command
        run: yarn release
